spring.application.name=trainer-stats-app
server.port=8082
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}
eureka.client.service-url.defaultZone=http://eureka-server:8761/eureka/
eureka.client.register-with-eureka=true
eureka.client.fetch-registry=true
correlation-id.header=${CORRELATION_ID_HEADER}
app.trainer-workload.queue-name=${APP_TRAINER_WORKLOAD_QUEUE_NAME}
app.mongo.uri=${APP_MONGO_URI}
spring.data.mongodb.auto-index-creation=true
